### PR TITLE
Added pragma: no cover to all FOUND files with TYPE_CHECKING.

### PR DESCRIPTION
**Pull request by ahobeost**

### CODE REVIEW

**Comment by zuckerruebe** [comment]
Wouldn't it be nicer to add a `if _tp.TYPE_CHECKING` line to `.coveragerc`?

**Comment by ahobeost** [comment]
> Wouldn't it be nicer to add a `if _tp.TYPE_CHECKING` line to `.coveragerc`?

Thanks @zuckerruebe.
I agree, and unfortunately that does not seem to work.
https://github.com/SPF-OST/pytrnsys_gui/blob/master/.coveragerc

image

https://coveralls.io/builds/70805707/source?filename=trnsysGUI%2FsinglePipePortItem.py

**Comment by ahobeost** [comment]
# pragma: no cover works for the entire if branch:
image

**Comment by ahobeost** [comment]
@zuckerruebe 
Would you like to use regex to fix this in .coveragerc, or can we deal with it like this?
https://coverage.readthedocs.io/en/latest/excluding.html#multi-line-exclusion-regexes

**Comment by zuckerruebe** [comment]
It's my understanding that we don't need a multi-line regex:

grafik

(https://coverage.readthedocs.io/en/latest/excluding.html#advanced-exclusion).

I might be wrong.

**Comment by zuckerruebe** [comment]
> > Wouldn't it be nicer to add a `if _tp.TYPE_CHECKING` line to `.coveragerc`?
> 
> Thanks @zuckerruebe. I agree, and unfortunately that does not seem to work. https://github.com/SPF-OST/pytrnsys_gui/blob/master/.coveragerc
> 
> image
> 
> https://coveralls.io/builds/70805707/source?filename=trnsysGUI%2FsinglePipePortItem.py

It would have to be a literal `if _tp.TYPE_CHECKING` (not the `_tp.`) as were really dealing with regex matches here.

**Comment by ahobeost** [comment]
> > > Wouldn't it be nicer to add a `if _tp.TYPE_CHECKING` line to `.coveragerc`?
> > 
> > 
> > Thanks @zuckerruebe. I agree, and unfortunately that does not seem to work. https://github.com/SPF-OST/pytrnsys_gui/blob/master/.coveragerc
> > image
> > https://coveralls.io/builds/70805707/source?filename=trnsysGUI%2FsinglePipePortItem.py
> 
> It would have to be a literal `if _tp.TYPE_CHECKING:` (note the `_tp.`) as were really dealing with regex matches here.

Nice catch!
Trying it now

**Comment by ahobeost** [comment]
Abandoning this pull request.
This issue is now already fixed in the main branch by using the updated regex.

**Pull request closed without merging**
