### PR TITLE
Removed deprecated link to standalone GUI documentation

### PR DESCRIPTION
**Pull request by martin-neugebauer**

### CODE REVIEW

**Comment by martin-neugebauer** [comment]
@zuckerruebe I have a hard time deducing the issue from the messages received. Furthermore, I don't see how they are connected to the small changes I did. Could you have a look? Thanks!

**Comment by zuckerruebe** [comment]
@martin-neugebauer Is this still relevant?

**Comment by martin-neugebauer** [comment]
The deprecated link is still there in the newest version. So yes, it's still relevant. But maybe it's easier to remove it again in the newest version and forget about this merge request.

**Comment by martin-neugebauer** [comment]
Should I remove it in the newest version and make a new merge request?

**Comment by zuckerruebe** [comment]
That would be great. Could you also please narrow the `except` clause, i.e. check the docs for what can actually be thrown and catch that otherwise `pylint` will complain.

**Comment by martin-neugebauer** [comment]
Superseeded by #279

**Pull request closed without merging**
