### PR TITLE
Pv ashp dhw sh mfh example

### PR DESCRIPTION
**Pull request by jschmidl**
Finished first version of PvAshpDhwShMfh example

### CODE REVIEW

**Comment by martin-neugebauer** [comment]
I successfully ran and processed the example case with the buttons in the GUI. The results check out. :-) So I think it looks good form that side. Right now the tests still fail for the storage tank on this branch. 
One more thing: Should we maybe set up the config-file such that it only executes one case and doesn't run the full parametric study? I think this would be better when simply trying out the example.

**Review by martin-neugebauer — CHANGES_REQUESTED** [review]
I successfully ran and processed the example case with the buttons in the GUI. The results check out. :-) So I think it looks good from that side. Right now the tests still fail for the storage tank on this branch.
One more thing: Should we maybe set up the config-file such that it only executes one case and doesn't run the full parametric study? I think this would be better when simply trying out the example.

**Comment by jschmidl** [comment]
> I successfully ran and processed the example case with the buttons in the GUI. The results check out. :-) So I think it looks good from that side. Right now the tests still fail for the storage tank on this branch. One more thing: Should we maybe set up the config-file such that it only executes one case and doesn't run the full parametric study? I think this would be better when simply trying out the example.

I changed the config file to include just 4 variations and thes tests work now as well.

**Review by martin-neugebauer — APPROVED** [review]

**Comment by martin-neugebauer** [comment]
Looks fine from my side. So feel free to go ahead and merge.

**Pull request merged**
