### PR TITLE
Package examples

### PR DESCRIPTION
**Pull request by zuckerruebe**
Distribute examples with our pypi package.

### CODE REVIEW

**Comment by martin-neugebauer** [comment]
Did you adjust the "ProjectFolder" entry in the json files of the diagram? This should be automatically be updated once the project is opened, but we should check. If you didn't change it the path saved in the json won't correspond to the actual

**Comment by zuckerruebe** [comment]
No, I didn't check. I will...what is this path actually used for?

**Comment by martin-neugebauer** [comment]
It tells the project its path (that could probably also be done in another way, e.g., by simply checking the location of the json file). The path is then used whenever files are exported (the hydraulic.ddck or the dck files etc.)

**Comment by martin-neugebauer** [comment]
I approve the request w. r. t. the paths, but there is a failed test.

**Review by martin-neugebauer — APPROVED** [review]

**Pull request merged**
